arch = { packages = [
  "archinstall",
  "base",
  "cpupower",
  "cups",
  "distrobox",
  "dolphin",
  "ecryptfs-utils",
  "flatpak",
  "flatpak-kcm",
  "framework-system",
  "fwupd",
  "icaclient",
  "intel-ucode",
  "kdeconnect",
  "mesa",
  "nvidia-open",
  "nvidia-prime",
  "nvidia-utils",
  "partitionmanager",
  "paru",
  "plasma-meta",
  "podman",
  "vulkan-radeon",
  "wireguard-tools",
] }
