arch = { packages = [
  "aerc",
  "android-tools",
  "atool",
  "base-devel",
  "bash-completion",
  "binutils",
  "bloaty",
  "bpftrace",
  "clang",
  "cmake",
  "code",
  "code-features",
  "code-marketplace",
  "curl",
  "fd",
  "fzf",
  "gcc",
  "gdb",
  "git",
  "git-filter-repo",
  "git-lfs",
  "github-cli",
  "glibc-locales",
  "htop",
  "imagemagick",
  "jq",
  "less",
  "lftp",
  "lsof",
  "ltrace",
  "man-pages",
  "meson",
  "metapac",
  "moreutils",
  "mtr",
  "ncdu",
  "neovim",
  "nmap",
  "numactl",
  "openssh",
  "patchelf",
  "perf",
  "pkgconf",
  "postgresql",
  "progress",
  "rclone",
  "ripgrep",
  "rizin",
  "rsync",
  "ruff",
  "rustup",
  "rz-cutter",
  "skopeo",
  "strace",
  "sudo",
  "tcpdump",
  "time",
  "traceroute",
  "tree",
  "ttf-hack",
  "uv",
  "wget",
  "which",
  "wireshark-cli",
  "wl-clipboard",
  "yay",
  "yt-dlp",
] }
flatpak = { repos = [
  { name = "system:flathub", options = { url = "https://dl.flathub.org/repo/" } },
], packages = [
  { name = "system:at.vintagestory.VintageStory", options = { remote = "flathub" } },
  { name = "system:com.borgbase.Vorta", options = { remote = "flathub" } },
  { name = "system:com.mojang.Minecraft", options = { remote = "flathub" } },
  { name = "system:com.protonvpn.www", options = { remote = "flathub" } },
  { name = "system:com.stremio.Service", options = { remote = "flathub" } },
  { name = "system:com.valvesoftware.Steam", options = { remote = "flathub" } },
  { name = "system:io.mpv.Mpv", options = { remote = "flathub" } },
  { name = "system:org.jellyfin.JellyfinServer", options = { remote = "flathub" } },
  { name = "system:org.kde.konsole", options = { remote = "flathub" } },
  { name = "system:org.kde.ktorrent", options = { remote = "flathub" } },
  { name = "system:org.mixxx.Mixxx", options = { remote = "flathub" } },
  { name = "system:org.mozilla.firefox", options = { remote = "flathub" } },
  { name = "system:org.nicotine_plus.Nicotine", options = { remote = "flathub" } },
] }
vscode = { packages = [
  "astral-sh.ty",
  "charliermarsh.ruff",
  "llvm-vs-code-extensions.vscode-clangd",
  "ms-ossdata.vscode-pgsql",
  "ms-python.debugpy",
  "ms-python.python",
  "ms-python.vscode-pylance",
  "ms-python.vscode-python-envs",
  "ms-toolsai.jupyter",
  "ms-toolsai.jupyter-keymap",
  "ms-toolsai.jupyter-renderers",
  "ms-toolsai.vscode-jupyter-cell-tags",
  "ms-toolsai.vscode-jupyter-slideshow",
  "ms-vscode-remote.remote-containers",
  "ms-vscode-remote.remote-ssh",
  "ms-vscode-remote.remote-ssh-edit",
  "ms-vscode.cpptools",
  "ms-vscode.remote-explorer",
  "rust-lang.rust-analyzer",
  "urld.nofrills",
  "vscodevim.vim",
] }
